spring:
  application:
    name: MovieMingle
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/moviemingle
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: ${DDL_AUTO}

server:
  servlet:
    contextPath: /api/v1

security:
  jwt:
    token:
      secret-key: k7lLhz2Zp8tHnlCUg0VwMdND7PRury7k
      issuer: moviemingle