spring:
  application:
    name: MovieMingle
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/moviemingle
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: ${DDL_AUTO}

server:
  port: 8081
  base-url: http://localhost:8081/api/v1
  servlet:
    contextPath: /api/v1

security:
  jwt:
    token:
      secret-key: k7lLhz2Zp8tHnlCUg0VwMdND7PRury7k
      issuer: moviemingle

frontend:
  base-url: http://localhost:4200

payment:
  stripe:
    api-key: sk_test_51PCICTDFODxhL5UQRkwOSyH7KARdvyvDTaYLSFSSQJ1gyVVKHWDGxfqsUBLfcTmCS7wVRew5oF9XVt4JdEEtUh4r00HYFQKwHx
    webhook-key: whsec_56d3a92756ae9abf8c1f868b932efbbc546ccbda9cf3a92f6b4232411e6691c4